name: Publish 1.0 docs

on:
  workflow_dispatch:

jobs:
  publish-docs:
    name: sbt publish
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-grpc'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8    

      - name: Build Documentation
        run: |-
          sbt "set ThisBuild / version := \"1.0.1\"; docs/paradox; unidoc"

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-grpc/1.0.1/
          mkdir -p target/nightly-docs/docs/pekko-grpc/1.0/
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-grpc/1.0.1/docs
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-grpc/1.0/docs
          rm -r docs/target/paradox/site/main/
          cp -r target/scala-2.12/unidoc target/nightly-docs/docs/pekko-grpc/1.0.1/api
          cp -r target/scala-2.12/unidoc target/nightly-docs/docs/pekko-grpc/1.0/api
          rm -r target/scala-2.12/unidoc

      - name: Upload 1.0.1 docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-grpc/1.0.1 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

      - name: Upload 1.0 docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-grpc/1.0 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
